[package]
name = "vec_rand"
version = "0.1.0"
edition = "2018"
description ="Vec generator to hold random contents."

license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "^0.8.4"
